-- ============================================================
-- SCHEMA — Fazenda Santa Rita · Sistema Financeiro
-- Rodar no Supabase: SQL Editor → New query → colar tudo → Run.
-- Pode ser rodado mais de uma vez sem erro (idempotente).
-- Colunas conferidas contra o código dos módulos (app, receitas,
-- endividamento, relatórios, config).
-- ============================================================

-- ── LANÇAMENTOS (contas a pagar) — app.html / relatórios / config ──
create table if not exists public.lancamentos (
  id              bigint generated by default as identity primary key,
  codigo          text,
  fornecedor      text not null,
  documento       text,
  solicitante     text,
  data_doc        date,
  vencimento      date,
  pagamento       date,
  status          text default 'A PAGAR',
  valor           numeric(14,2) default 0,
  conta           text,
  correntista     text,
  fazenda         text,
  safra           text,
  cultura         text,
  cg              text,
  lancador        text,
  historico       text,
  forma_pagamento text default 'BOLETO',
  cnpj            text,
  chave_pix       text,
  codigo_barras   text,
  boleto_path     text,
  boleto_paths    text[],
  nf_path         text,
  nf_paths        text[],
  recibo_path     text,
  created_at      timestamptz default now()
);
create index if not exists idx_lanc_vencimento on public.lancamentos(vencimento);
create index if not exists idx_lanc_status     on public.lancamentos(status);
create index if not exists idx_lanc_fazenda    on public.lancamentos(fazenda);
create index if not exists idx_lanc_fornecedor on public.lancamentos(fornecedor);

-- ── FORNECEDORES (autocomplete + CNPJ) — app.html ──
create table if not exists public.fornecedores (
  id        bigint generated by default as identity primary key,
  nome      text not null,
  cnpj      text,
  criado_em timestamptz default now()
);
create index if not exists idx_fornecedores_nome on public.fornecedores(nome);

-- ── RECEITAS (vendas) — app-receitas.html ──
create table if not exists public.receitas (
  id                 bigint generated by default as identity primary key,
  produto            text,
  comprador          text,
  cnpj_cpf           text,
  data_receb         date,
  status             text default 'A RECEBER',
  valor              numeric(14,2) default 0,      -- valor líquido
  fazenda            text,
  safra              text,
  historico          text,
  lancador           text,
  -- campos de grãos (soja/milho/sorgo)
  numero_contrato    text,
  quantidade_kg      numeric(14,2),
  sacas              numeric(14,4),
  valor_unitario     numeric(14,4),
  descontos          numeric(14,2),
  valor_bruto        numeric(14,2),
  contas_recebimento jsonb,                        -- rateio [{conta, valor}]
  comprovante_path   text,
  comprovante_paths  text[],
  created_at         timestamptz default now()
);
create index if not exists idx_rec_data   on public.receitas(data_receb);
create index if not exists idx_rec_status on public.receitas(status);

-- ── ENDIVIDAMENTO: CONTRATOS — app-endividamento.html ──
create table if not exists public.endiv_contratos (
  id              bigint generated by default as identity primary key,
  titular         text,
  numero_contrato text,
  banco           text,
  modalidade      text,
  categoria       text,          -- Custeio | Investimento | CPR | Aditivo
  tipo            text,          -- CURTO PRAZO | LONGO PRAZO
  taxa            numeric(10,6), -- decimal (0,14 = 14% a.a.)
  periodicidade   text,
  moeda           text,
  saldo_devedor   numeric(16,2),
  data_contrato   date,
  data_fim        date,
  obs             text,
  created_at      timestamptz default now()
);

-- ── ENDIVIDAMENTO: PARCELAS — app-endividamento.html ──
create table if not exists public.endiv_lancamentos (
  id              bigint generated by default as identity primary key,
  contrato_id     bigint,
  numero_contrato text,
  titular         text,
  banco           text,
  modalidade      text,
  categoria       text,
  tipo            text,
  taxa            numeric(10,6),
  ano             text,          -- 'ANO 2026'
  mes_parcela     int,
  data_parcela    date,
  valor_parcela   numeric(16,2),
  saldo_devedor   numeric(16,2),
  status          text default 'A PAGAR',  -- A PAGAR | PAGO | ADITADO
  data_pagamento  date,
  juros_pagos     numeric(16,2),
  conta           text,
  created_at      timestamptz default now()
);
create index if not exists idx_endl_contrato on public.endiv_lancamentos(contrato_id);
create index if not exists idx_endl_data     on public.endiv_lancamentos(data_parcela);

-- ── STORAGE: bucket privado para anexos (boletos, NFs, recibos, comprovantes) ──
insert into storage.buckets (id, name, public)
values ('anexos', 'anexos', false)
on conflict (id) do nothing;

-- ── RLS ─────────────────────────────────────────────────────
-- Policies PERMISSIVAS de partida (o login do app é feito no navegador,
-- não no Supabase). Endurecer antes de liberar para uso comercial.
do $$
declare t text;
begin
  foreach t in array array['lancamentos','fornecedores','receitas','endiv_contratos','endiv_lancamentos'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "app_all" on public.%I', t);
    execute format('create policy "app_all" on public.%I for all using (true) with check (true)', t);
  end loop;
end $$;

drop policy if exists "anexos_all" on storage.objects;
create policy "anexos_all" on storage.objects for all
  using (bucket_id = 'anexos') with check (bucket_id = 'anexos');

-- Conferência: deve listar as 5 tabelas
select table_name from information_schema.tables
where table_schema = 'public'
  and table_name in ('lancamentos','fornecedores','receitas','endiv_contratos','endiv_lancamentos')
order by 1;
